[build]
pre-build = [
  # rust-bindgen dependencies: llvm-dev libclang-dev (>= 5.0) clang (>= 5.0)
  "apt-get update && apt-get install -y --no-install-recommends llvm-dev libclang-6.0-dev clang-6.0 libssl-dev",
]
