#!/bin/sh

cargo check --all-features
if [ $? -ne 0 ]; then
    echo "Pre-push hook failed: cargo check detected errors."
    exit 1
fi

cargo clippy --workspace --all-features --all-targets -- -D warnings
if [ $? -ne 0 ]; then
    echo "Pre-push hook failed: cargo clippy detected warnings or errors."
    exit 1
fi

cargo fmt --all --check
if [ $? -ne 0 ]; then
    echo "Pre-push hook failed: cargo fmt detected formatting issues."
    exit 1
fi

exit 0
