---
name: Load artifacts

on:
  workflow_dispatch:
  workflow_call:

jobs:
  dump:
    name: katana
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: dump-katana
