name: 'Changelog Workflow'
on:
  workflow_dispatch:
  workflow_call:

jobs:
  # Enforces the update of a changelog file on every pull request
  changelog:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: dangoslen/changelog-enforcer@v3
        with:
          skipLabels: 'skip-changelog, dependencies'
