# Runs `cargo update` periodically.

name: Update Dependencies

on:
  schedule:
    # Run weekly
    - cron: 0 0 * * MON
  workflow_dispatch:
    # Needed so we can run it manually

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH: cargo-update
  TITLE: "chore(deps): weekly `cargo update`"
  BODY: |
    Automation to keep dependencies in `Cargo.lock` current.

    <details><summary><strong>cargo update log</strong></summary>
    <p>

    ```log
    $cargo_update_log
    ```

    </p>
    </details>

permissions:
  checks: write
  contents: write
  pull-requests: write

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly

      - name: Cargo update
        # Remove first line that always just says "Updating crates.io index"
        run: |
          cargo update --color never 2>&1 | sed '/crates.io index/d' | tee -a cargo_update.log

      - name: Craft commit message and PR body
        id: msg
        run: |
          export cargo_update_log="$(cat cargo_update.log)"

          echo "commit_message<<EOF" >> $GITHUB_OUTPUT
          printf "$TITLE\n\n$cargo_update_log\n" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" | envsubst >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - uses: actions/create-github-app-token@v1
        id: github_token
        with:
          app-id: ${{ secrets.KAKAROT_BOT_APP_ID }}
          private-key: ${{ secrets.KAKAROT_BOT_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ steps.github_token.outputs.token }}
          add-paths: ./Cargo.lock
          commit-message: ${{ steps.msg.outputs.commit_message }}
          title: ${{ env.TITLE }}
          body: ${{ steps.msg.outputs.body }}
          branch: ${{ env.BRANCH }}
