name: Trunk

on:
  workflow_call:

permissions:
  checks: write # For trunk to post annotations
  contents: read # For repo checkout

jobs:
  trunk-check:
    name: Trunk
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: rustup update
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"

      - name: Trunk Check
        uses: trunk-io/trunk-action@v1
