name: Update Submodule

# on:
#   schedule:
#     - cron: "0 0 * * *" # Runs daily at midnight
#   workflow_dispatch: # Allows manual triggering

on: [pull_request]

jobs:
  update-submodule:
    permissions:
        contents: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: recursive # Checkout submodules

      - name: Get Latest Release Tag
        id: get_latest_release
        run: |
          latest_release=$(curl -s https://api.github.com/repos/kkrt-labs/kakarot/releases/latest | jq -r .tag_name)
          echo "latest_release=${latest_release}" >> $GITHUB_ENV

      - name: Check Current Submodule Commit
        id: check_submodule_commit
        run: |
          cd lib/kakarot
          current_commit=$(git rev-parse HEAD)
          latest_commit=$(git ls-remote https://github.com/kkrt-labs/kakarot.git ${{ env.latest_release }} | awk '{print $1}')
          echo "current_commit=${current_commit}" >> $GITHUB_ENV
          echo "latest_commit=${latest_commit}" >> $GITHUB_ENV
          cd -

      - name: Update Submodule
        if: env.current_commit != env.latest_commit
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          cd lib/kakarot
          git fetch --all --tags
          git checkout tags/${{ env.latest_release }}
          cd -
          git checkout -b update-kakarot-submodule-${{ env.latest_release }}
          git add lib/kakarot
          git commit -m "Update kakarot submodule to latest release ${{ env.latest_release }}"
          git push origin update-kakarot-submodule-${{ env.latest_release }}

      - name: Create Pull Request
        if: env.current_commit != env.latest_commit
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/kkrt-labs/kakarot-rpc/pulls \
            -d '{"title":"Update kakarot submodule to ${{ env.latest_release }}","head":"update-kakarot-submodule-${{ env.latest_release }}","base":"main","body":"This PR updates the kakarot submodule to the latest release ${{ env.latest_release }}."}'
